import fs from 'fs';

const iconMap = {
  'folder-open': 'folder-open',
  'file-text': 'file-text',
  'message-square': 'message-square',
  settings: 'gear',
  palette: 'palette',
  bot: 'robot',
  x: 'x',
  search: 'search',
  plus: 'plus',
  'trash-2': 'trash-can',
  eye: 'eye',
  edit: 'edit',
  'refresh-cw': 'refresh',
  download: 'download',
  upload: 'upload',
  save: 'save',
  lock: 'lock',
  key: 'key',
  globe: 'globe',
  database: 'database',
  user: 'user',
  layout: 'layout-grid',
  inbox: 'inbox',
  tag: 'tag',
  hashtag: 'hashtag',
  'bar-chart-2': 'bar-chart',
  target: 'target',
  link: 'link',
  plug: 'plug',
  pencil: 'pencil',
  copy: 'copy',
  'share-2': 'share-alt',
  flame: 'flame',
  'sliders-horizontal': 'sliders',
  brain: 'brain',
  play: 'play',
  pause: 'pause',
  square: 'square',
  clock: 'clock',
  check: 'check',
  home: 'home',
  image: 'image',
  video: 'video',
  audio: 'audio',
  mail: 'mail',
  phone: 'phone',
  map: 'map',
  calendar: 'calendar',
  bell: 'bell',
  book: 'book',
  'book-open': 'book-open',
  file: 'file',
  folder: 'folder',
  archive: 'archive',
  trash: 'trash',
  'folder-plus': 'folder-plus',
  'folder-minus': 'folder-minus',
  'folder-x': 'folder-x',
  'folder-check': 'folder-check',
  tags: 'tags',
  barcode: 'barcode',
  qrcode: 'qrcode',
  keyboard: 'keyboard',
  mouse: 'mouse',
  printer: 'printer',
  monitor: 'monitor',
  laptop: 'laptop',
  tablet: 'tablet',
  mobile: 'mobile',
  headphones: 'headphones',
  microphone: 'microphone',
  camera: 'camera',
  music: 'music',
  volume: 'volume-high',
  'volume-x': 'volume-x',
  lightbulb: 'lightbulb',
  battery: 'battery-full',
  wifi: 'wifi',
  bluetooth: 'bluetooth',
  gps: 'map-marker',
  compass: 'compass',
  thermometer: 'thermometer',
  droplet: 'droplet',
  wind: 'wind',
  cloud: 'cloud',
  sun: 'sun',
  moon: 'moon',
  star: 'star',
  heart: 'heart',
  'thumbs-up': 'thumbs-up',
  'thumbs-down': 'thumbs-down',
  smile: 'smile',
  frown: 'frown',
  trophy: 'trophy',
  award: 'award',
  medal: 'medal',
  crown: 'crown',
  shield: 'shield',
  'shield-check': 'shield-check',
  'shield-x': 'shield-x',
  unlock: 'unlock',
  keyhole: 'keyhole',
  'eye-off': 'eye-off',
  'search-minus': 'search-minus',
  'search-plus': 'search-plus',
  'x-circle': 'x-circle',
  'check-circle': 'check-circle',
  minus: 'minus',
  'plus-circle': 'plus-circle',
  'alert-circle': 'exclamation-circle',
  'info-circle': 'info-circle',
  'help-circle': 'help-circle',
  'question-circle': 'question-circle',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  'chevron-up': 'chevron-up',
  'chevron-down': 'chevron-down',
  'arrow-left': 'arrow-left',
  'arrow-right': 'arrow-right',
  'arrow-up': 'arrow-up',
  'arrow-down': 'arrow-down',
  move: 'move',
  maximize: 'maximize',
  minimize: 'minimize',
  square: 'square',
  circle: 'circle',
  diamond: 'diamond',
  hexagon: 'hexagon',
  octagon: 'octagon',
  pentagon: 'pentagon',
  triangle: 'triangle',
  'cloud-sun': 'cloud-sun',
  'cloud-moon': 'cloud-moon',
  'cloud-rain': 'cloud-rain',
  'cloud-lightning': 'cloud-lightning',
  snowflake: 'snowflake',
  tornado: 'tornado',
  umbrella: 'umbrella',
  mountain: 'mountain',
  'tree-pine': 'tree-pine',
  'tree-deciduous': 'tree-deciduous',
  'palm-tree': 'palm-tree',
  cactus: 'cactus',
  flower: 'flower',
  leaf: 'leaf',
  cherry: 'cherry',
  apple: 'apple',
  orange: 'orange',
  grape: 'grape',
  watermelon: 'watermelon',
  pizza: 'pizza',
  hamburger: 'hamburger',
  hotdog: 'hotdog',
  taco: 'taco',
  soup: 'soup',
  utensils: 'utensils',
  coffee: 'coffee',
  tea: 'tea',
  wine: 'wine',
  beer: 'beer',
  cocktail: 'cocktail',
  soda: 'soda',
  'glass-water': 'glass-water',
  'mug-hot': 'mug-hot',
  'ice-cream': 'ice-cream',
  cake: 'cake',
  candy: 'candy',
  cookie: 'cookie',
  popcorn: 'popcorn',
  'french-fries': 'french-fries',
  sandwich: 'sandwich',
  salad: 'salad',
  steak: 'steak',
  bone: 'bone',
  fish: 'fish',
  shrimp: 'shrimp',
  crab: 'crab',
  lobster: 'lobster',
  drumstick: 'drumstick',
  wheat: 'wheat',
  rice: 'rice',
  corn: 'corn',
  beans: 'beans',
  peanut: 'peanut',
  coconut: 'coconut',
  honey: 'honey',
  butter: 'butter',
  milk: 'milk',
  cheese: 'cheese',
  egg: 'egg',
  bacon: 'bacon',
  sausage: 'sausage',
  turkey: 'turkey',
  chicken: 'chicken',
  cow: 'cow',
  pig: 'pig',
  sheep: 'sheep',
  goat: 'goat',
  horse: 'horse',
  dog: 'dog',
  cat: 'cat',
  bird: 'bird',
  bunny: 'bunny',
  frog: 'frog',
  snake: 'snake',
  turtle: 'turtle',
  lizard: 'lizard',
  spider: 'spider',
  bug: 'bug',
  ant: 'ant',
  bee: 'bee',
  ladybug: 'ladybug',
  butterfly: 'butterfly',
  mosquito: 'mosquito',
  fly: 'fly',
  worm: 'worm',
  snail: 'snail',
  octopus: 'octopus',
  jellyfish: 'jellyfish',
  shark: 'shark',
  whale: 'whale',
  dolphin: 'dolphin',
  seahorse: 'seahorse',
  starfish: 'starfish',
  shell: 'shell',
  coral: 'coral',
  anchor: 'anchor',
  boat: 'boat',
  ship: 'ship',
  'cruise-ship': 'cruise-ship',
  submarine: 'submarine',
  plane: 'plane',
  helicopter: 'helicopter',
  rocket: 'rocket',
  car: 'car',
  truck: 'truck',
  bus: 'bus',
  train: 'train',
  tram: 'tram',
  taxi: 'taxi',
  scooter: 'scooter',
  bicycle: 'bicycle',
  motorcycle: 'motorcycle',
  wheelchair: 'wheelchair',
  hiking: 'hiking',
  skiing: 'skiing',
  snowboarding: 'snowboarding',
  surfing: 'surfing',
  camping: 'camping',
  tent: 'tent',
};

const filesToFix = [
  'src/views/UserChat.js',
  'src/views/KBList.js',
  'src/views/KBDetail.js',
  'src/utils/helpers.js',
  'src/main.js',
  'src/components/TemplateSelector.js',
  'src/components/KBCard.js',
  'src/components/EditKBModal.js',
  'src/components/DataSourceForm.js',
  'src/components/CreateKBModal.js',
  'src/components/ChatSidebar.js',
  'src/components/ChatContainer.js',
  'src/components/Sidebar.js',
  'src/components/Modal.js',
];

for (const filePath of filesToFix) {
  try {
    let content = fs.readFileSync(filePath, 'utf-8');

    content = content.replace(
      /class="lucide lucide-([^"]+)"/g,
      (match, iconName) => {
        const faIconName = iconMap[iconName] || iconName;
        return `class="fa-solid fa-${faIconName}"`;
      }
    );

    fs.writeFileSync(filePath, content, 'utf-8');
    console.log(`Fixed icons in ${filePath}`);
  } catch (err) {
    console.error(`Error processing ${filePath}:`, err);
  }
}

console.log('All files processed!');
